// HolodexPlusExtension — generate placeholder SVG icons and save as PNG-like data URIs
// Run this ONCE in a browser console or Node.js with canvas to produce real PNGs.
// For quick sideloading, you can use any 16x16 / 48x48 / 128x128 PNG images renamed to:
//   icons/icon16.png
//   icons/icon48.png
//   icons/icon128.png

// --- Minimal SVG icon embedded as data (can be referenced directly in HTML if needed) ---
// The actual PNG files need to be placed in the icons/ folder manually,
// or generated by running: node generate_icons.js

const { createCanvas } = require('canvas'); // npm install canvas
const fs = require('fs');
const path = require('path');

const sizes = [16, 48, 128];

if (!fs.existsSync('icons')) fs.mkdirSync('icons');

for (const size of sizes) {
  const canvas = createCanvas(size, size);
  const ctx = canvas.getContext('2d');

  // Background
  const grad = ctx.createLinearGradient(0, 0, size, size);
  grad.addColorStop(0, '#a78bfa');
  grad.addColorStop(1, '#60a5fa');
  ctx.fillStyle = grad;
  roundRect(ctx, 0, 0, size, size, size * 0.18);
  ctx.fill();

  // "H+" text
  ctx.fillStyle = '#ffffff';
  ctx.font = `bold ${Math.round(size * 0.45)}px Arial`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('H+', size / 2, size / 2);

  const buffer = canvas.toBuffer('image/png');
  fs.writeFileSync(path.join('icons', `icon${size}.png`), buffer);
  console.log(`icons/icon${size}.png written`);
}

function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}
